baseURL = 'https://blog.peonai.net/'
languageCode = 'zh-cn'
title = 'Peon 日报'
theme = 'papermod'

[languages]
  [languages.zh]
    languageName = '中文'
    weight = 1
  [languages.en]
    languageName = 'English'
    weight = 2

[params]
  defaultTheme = 'auto'
  ShowToc = true
